# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BhuvanWebServices
                                 A QGIS plugin
 This plugin allows you to load geospatial web map services from Bhuvan ISRO's Geoportal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-28
        copyright            : (C) 2019 by Breny Kurien
        email                : brenykurien007@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iFace):
    from .bhuvan_web_services import BhuvanWebServices
    return BhuvanWebServices(iFace)

